### ISSUE TITLE
Additional Instructions for Install

### ISSUE THREAD

**Issue by abel408** [durabledata/greenbone-community-k8s#1]
Hi,

I'm hoping you could provide some additional instructions that may be needed for the basic deployment. I tried applying the manifest as is, but all pods are in CrashLoopBackOff or error state.

Thanks!

**Comment by durabledata** [comment]
Kubernetes of any type isn't trivial so you will need some knowledge of it to successfully deploy.

If all the pods are crashing, the issue might be a mismatch in the cpu architecture on the images or a number of other things so it is difficult to guess.

The first thing to do is to describe each of the pods and post the errors they are showing.

**Comment by abel408** [comment]
Thanks. I didn;t even realize these were arm images. Changing them seemed to fix. 

The readiness probe fails though. Looks like GSA cannot bind to port 80:

`gsad main:WARNING:2024-01-24 18h41.26 utc:13: Binding to port 80 failed, trying default port 9392 next.`

`kubectl get service -n gvm
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
mqtt-broker   ClusterIP   10.152.183.194   <none>        1883/TCP   30h
broker        ClusterIP   10.152.183.237   <none>        1883/TCP   30h
gsa-service   ClusterIP   10.152.183.153   <none>        80/TCP     30h`

Any ideas? Do I need to do anything with the startup script or should the execute on it's own? Thanks for the help. I'm still very much learning kubernetes so it is very likely that I'm doing something wrong.

**Comment by durabledata** [comment]
Can you describe your environment?

**Comment by abel408** [comment]
I'm using microk8s on Ubuntu.

**Comment by durabledata** [comment]
As stated in the readme this is tested on k3s on ubuntu. I don't see why it wouldn't work on microk8s, assuming you are deploying the non-kilo version, because that is going to be specific to your k8s deployment.

It seems like there's a conflict with that port. Do you have other apps deployed on that cluster that might conflict?

**Comment by abel408** [comment]
I have other services on this cluster running on port 80. That shouldn't be a problem though as this isn't configured as a nodeport correct?

**Comment by durabledata** [comment]
The error looks like an issue within the container, as if it doesn't have permissions to bind port 80 or something already bound to it, like if gsa was being run twice. Double check the container are using, the amd64 equivalent is linked below. If it can't bind to 80 but can bind to 9392, you could update the deployment config for the container and service to point at it.

Root cause could also be some security policy you have where the pod isn't running under a context allowing this binding. You could shell into the pod to do some troubleshooting.

Depending on what utilities are on the gsa pod you could do a netstat to see if the port is already bound. You could also look at the entrypoint to see what's being run on start and run that yourself from within the pod. You could use a busybox container in that deployment and nc or curl to see if 80 or 9392 are up. You could run the same pod in docker and compare the situation between the docker container and the k8s one. The application in the pod is open source so you can inspect that and the entrypoint in the container to see what to expect.

In general I'm happy to help but there's only so much I can do without visibility into your environment. Please troubleshoot on the items above and provide well formatted errors, tests, and context of your configurations. If I don't have that I won't be equipped to help much more.

https://hub.docker.com/layers/greenbone/gsa/latest/images/sha256-bd817922d58715397d76ed64e93901288889c8685158dace7109d6392b592232?context=explore&tab=vulnerabilities

**Comment by abel408** [comment]
I was able to bind to port 9392 and then use traefik and metallb to get the service to run on port 80. I think this may have to do with non-root users not able to bind to ports under 1024.

**Comment by abel408** [comment]
My reports seem very slow to load. Wondering if you have the same issue. Thanks

**Comment by durabledata** [comment]
I didn't have an issue with slowly loading reports. However, the definitions can take a long time to load the first time before you can run any scans, and the scans can take a long time depending on what they are. But once I have definitions and a scan is complete, reports load fine.

**Comment by durabledata** [comment]
Original issue is solved.
